### ISSUE TITLE
Broken links in readme files

### ISSUE THREAD

**Issue by narner** [chirp/chirpino#1]
Hello! Just wanted to let you know that I noticed a few broken links:

-In the main [readme.md file] (https://github.com/chirp/chirpino/blob/master/readme.md) the 'our page for developers' link is broken. 

-In the [ArduinoMega readme.md file] (https://github.com/chirp/chirpino/tree/master/Chirpino%20for%20Arduino%20Mega), the 'ChirpinoSing library' link is broken

By the way, this library looks great, can't wait to start using it!

**Comment by bitrivers** [comment]
Hi  - many thanks for the heads up on the links. They were indeed all well broken, but might have a better chance in life now. Very pleased to hear your enthusiasm for the library, hope it gets you chirping with ease. Cheers - J
