### ISSUE TITLE
Error compiling "Make Codes" sketch

### ISSUE THREAD

**Issue by narner** [chirp/chirpino#2]
Currently, the `Make Codes` example sketch does not compile due to the error below:

`MakeCodes.ino:15:26: fatal error: ChirpinoLink.h: No such file or directory
compilation terminated.
Error compiling.`

Below is a screenshot of the folder structure after downloading the Chirpino repo:

![screen shot 2015-09-07 at 3 37 32 pm](https://cloud.githubusercontent.com/assets/2131591/9722205/bbf6354c-5576-11e5-9ea5-e25e8224d352.png)

**Comment by bitrivers** [comment]
Hi Nick - It's working for me. Have you installed ChirpinoLink as a library? Are you accessing MakeCodes from the file/examples menu within the IDE?

**Comment by narner** [comment]
Ah! Yes, the problem was that I had installed the ChirpinoSing as a library, but not ChirpinoLink :/ 
However, when I went to add ChirpinoLink as a library using "Include Library / Add .ZIP Library", I got the error below:

```
The library "ChirpinoLink for Arduinos" cannot be used.
Library names must contain only basic letters and numbers.
(ASCII only and no spaces, and it cannot start with a number)
```

**Comment by bitrivers** [comment]
The library is the folder inside "ChirpinoLink for Arduinos" called ChirpinoLink. Don't forget, you'll also need to obtain an API key and edit it into the example program.
